export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER';
export const VALIDATE_REQUEST = 'VALIDATE_REQUEST';

export const RETRIEVE_TODAY_RESTAURANT = 'RETRIEVE_TODAY_RESTAURANT';
export const RETRIEVE_RESTAURANT_DISHES = 'RETRIEVE_RESTAURANT_DISHES';
export const ADD_DISH_TO_CART = 'ADD_DISH_TO_CART';
export const REMOVE_DISH_FROM_CART = 'REMOVE_DISH_FROM_CART';
export const UPDATE_USER_ORDER = 'UPDATE_USER_ORDER';
export const REORDER_USER_ORDER = 'REORDER_USER_ORDER';
export const COPY_USER_ORDER = 'COPY_USER_ORDER';
export const VIEW_USER_ORDER_HISTORY = 'VIEW_USER_ORDER_HISTORY';
export const VIEW_ALL_ORDER_HISTORY = 'VIEW_ALL_ORDER_HISTORY';